kind: Service
apiVersion: v1
metadata:
  name: hello-app-service-canary
spec:
  type: NodePort
  selector:
    app: hello-app
    track: canary
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment-canary
  labels:
    app: hello-app
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: hello-app
      track: canary
  template:
    metadata:
      labels:
        app: hello-app
        track: canary
    spec:
      containers:
      - name: hello-app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
